development:
  adapter: postgresql
  database: cable
  username: <%= ENV["MAINO_CONNECT_DATABASE_USER"] %>
  password: <%= ENV["MAINO_CONNECT_DATABASE_PASSWORD"] %>
  host: <%= ENV["MAINO_CONNECT_DATABASE_HOST"] %>
  port: <%= ENV["MAINO_CONNECT_DATABASE_PORT"] || 5432 %>

production:
  adapter: postgresql
  database: cable
  username: <%= ENV["MAINO_CONNECT_DATABASE_USER"] %>
  password: <%= ENV["MAINO_CONNECT_DATABASE_PASSWORD"] %>
  host: <%= ENV["MAINO_CONNECT_DATABASE_HOST"] %>
  port: <%= ENV["MAINO_CONNECT_DATABASE_PORT"] || 5432 %>
