default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: maino_connect_development

test:
  <<: *default
  database: maino_connect_test

production:
  production:
  <<: *default
  database: maino_connect_production
  username: <%= ENV["MAINO_CONNECT_DATABASE_USER"] %>
  password: <%= ENV["MAINO_CONNECT_DATABASE_PASSWORD"] %>
  host: <%= ENV["MAINO_CONNECT_DATABASE_HOST"] %>
  port: <%= ENV["MAINO_CONNECT_DATABASE_PORT"] || 5432 %>


